### ISSUE TITLE
boto incompatibility

### ISSUE THREAD

**Issue by hoenth** [sankalpjonn/elchapo#1]
Thank you for creating this. It is exactly what I was looking for. 

When I installed the packages, I received the following error message: ERROR: boto3 1.4.7 has requirement botocore<1.8.0,>=1.7.0, but you'll have botocore 1.12.54 which is incompatible.

Should boto3 be upgraded to the latest, i.e. 1.14.26? 

This will be my first python project, so I apologize in advance if this is obvious or not needed.

**Comment by sankalpjonn** [comment]
Hello Tom,

This should not be a problem. It will automatically fix the compatibility
issues and install the necessary packages. Are you able to run the server ?
If you are then it should be fine.
